#!/bin/sh

# source: https://www.youtube.com/watch?v=SkxdcOea-rE
PLAYGROUNDS_DIR="/tmp/rust-playgrounds"
TIMESTAMP=$(date +"%Y%m%d%H%M%S")
PROJECT_DIR="${PLAYGROUNDS_DIR}/playground${TIMESTAMP}"

cargo new "$PROJECT_DIR"
cd "$PROJECT_DIR" || exit

# Add dependencies to Cargo.toml
for CRATE in "$@"; do
	sed "/^\[dependencies\]/a $CRATE = \"*\"" -i Cargo.toml
done

tmux new-session \; \
	send-keys "vim ./src/main.rs" C-m \; \
	split-window -h \; \
	send-keys "cargo watch -q -c -w src/ -x run" C-m \; \
	select-pane -L
