#!/usr/bin/bash

PLAYGROUNDS_DIR="$HOME/go/src"
TIMESTAMP=$(date +"%Y%m%d%H%M%S")
PROJECT_DIR="${PLAYGROUNDS_DIR}/playground${TIMESTAMP}"

mkdir "$PROJECT_DIR"
cd "$PROJECT_DIR" || exit
echo -e 'package main\n\nimport "fmt"\n\nfunc main(){\n\tfmt.Println("hello")\n}' >>main.go
go mod init

for dependency in "$@"; do
	$dependency
done

tmux new-session \; \
	send-keys "vim ./main.go" C-m \; \
	split-window -v \; \
	send-keys "watchexec 'clear;go run main.go'" C-m \; select-pane -U
